apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payment-route
  namespace: prod
spec:
  parentRefs:
  - name: prod-gateway
  rules:
  - backendRefs:
    - name: payment-stable
      port: 80
