apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: p95-latency
spec:
  metrics:
  - name: p95
    interval: 30s
    count: 5

    successCondition: len(result) > 0 && result[0] < 500
    failureCondition: len(result) == 0 || result[0] >= 500

    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          query: |
          histogram_quantile(0.95, 
            sum(rate(istio_request_duration_milliseconds_bucket{
              reporter="destination",
              destination_workload="demo-app"
            }[1m])) by (le)
          )

